name: Run tests
on: [push]
jobs:
  test:
    env:
      DATABASE_URL: postgresql://test_user:test_password@localhost/test_db?pool=5
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:11
        env:
          POSTGRES_USER: test_user
          POSTGRES_DB: test_db
          POSTGRES_PASSWORD: test_password
        ports: ["5432:5432"]
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
    - run: yarn install
    - run: bundle exec rake